# Generated by Django 4.2.8 on 2023-12-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('cheap', 'Дешёвые'), ('comfortable', 'Комфортные'), ('vip', 'V.I.P.')], max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('details', models.TextField()),
            ],
        ),
    ]
